stages:
  - build
  - deploy

build project:
  image: node:20.5.1
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

# netlify:
#   stage: deploy
#   image: node:20.5.1
#   script:
#     - npm install -g netlify-cli
#     - netlify deploy --dir=build --prod

